create database Library2;
CREATE TABLE Author
(
Id INT NOT NULL IDENTITY PRIMARY KEY,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL
)
CREATE TABLE Publisher
(
Id INT NOT NULL IDENTITY PRIMARY KEY,
PublisherName VARCHAR(100) NOT NULL,
Address VARCHAR(100) NOT NULL
)
CREATE TABLE Book
(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Title VARCHAR(50) NOT NULL,
IdAuthor INT NOT NULL FOREIGN KEY REFERENCES
Author(Id),
Pages INT,
Price INT,
IdPublisher INT NOT NULL FOREIGN KEY
REFERENCES Publisher(Id)
)